package com.example.fitnesstracker;

import jakarta.persistence.*;

import java.time.LocalDate;

/**
 * Represents a single running record in the Fitness Tracker application.
 * Each RunRecord stores the route name, number of miles run,
 * and the date the run was completed.
 */
@Entity
public class RunRecord {


    /**
     * Unique identifier for each run record.
     * This value is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the running route.
     */
    private String route;

    /**
     * Number of miles run.
     */
    private double miles;

    /**
     * Date of the run.
     */
    private LocalDate date;

    /**
     * Default constructor required by JPA.
     */
    public RunRecord() {
    }

    /**
     * Creates a new RunRecord with the given route, miles, and date.
     *
     * @param route
     * @param miles
     * @param date
     */
    public RunRecord(String route, double miles, LocalDate date) {
        this.route = route;
        this.miles = miles;
        this.date = date;
    }

    /**
     * Gets the record ID.
     *
     * @return
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the record ID.
     *
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the route name.
     *
     * @return
     */
    public String getRoute() {
        return route;
    }

    /**
     * Sets the route name.
     *
     * @param route
     */
    public void setRoute(String route) {
        this.route = route;
    }

    /**
     * Gets the miles run.
     *
     * @return
     */
    public double getMiles() {
        return miles;
    }

    /**
     * Sets the miles run.
     *
     * @param miles
     */
    public void setMiles(double miles) {
        this.miles = miles;
    }

    /**
     * Gets the date of the run.
     *
     * @return
     */
    public LocalDate getDate() {
        return date;
    }

    /**
     * Sets the date of the run.
     *
     * @param date
     */
    public void setDate(LocalDate date) {
        this.date = date;
    }
}